### ISSUE TITLE
Add App Description to the consumers list

### ISSUE THREAD

**Issue by ichaib** [OpenBankProject/API-Manager#10]
Show first 80 chars

**Comment by sebtesobe** [comment]
Done, although i don't quite like the way it's done, because it interferes with the (not yet added) tablesorter plugin which would allow awesome sorting client-side. 

I might have forgotten, but why is the description important for the list of all consumers (it is available on the detail page)?

Please test: https://apimanagersandbox.openbankproject.com/consumers/
