### ISSUE TITLE
BUG: Buttons on Consumer list are not appearing correctly

### ISSUE THREAD

**Issue by ichaib** [OpenBankProject/API-Manager#12]

**Comment by sebtesobe** [comment]
That is because Redirect URL was added to the list view instead of the detail view

**Comment by sebtesobe** [comment]
I reckon it's fixed, please test:

https://apimanagersandbox.openbankproject.com/consumers/

**Comment by simonredfern** [comment]
The buttons are still too wide big:

<img width="1057" alt="api_manager_consumers" src="https://cloud.githubusercontent.com/assets/485218/24204769/c61729f6-0f19-11e7-9293-53a77ecd8444.png">

**Comment by simonredfern** [comment]
We can see the original (good) design here: https://github.com/OpenBankProject/API-Manager/wiki

**Comment by sebtesobe** [comment]
@simonredfern Your issue is somethings else than @ichaib meant. 

I believe your browser viewport has become too small to display 'large' size, so the responsive design kicked in to display 'medium'. Unfortunately, all buttons together become too wide for 'medium' size, so they are vertically stacked already in that size. We would need icons, shorter text or smaller font size. I'd probably try the latter, maybe just one pixel smaller would be sufficient already.

**Comment by sebtesobe** [comment]
I just tried, but decreasing the font size is not the winner: We would need to go down to 8px (instead of 14px) and that is barely legible. Carefully crafting paddings could help. Or bootstrap's grid being 24 units wide, not 12. 
@simonredfern Can we ditch 'Last Minute' ?

**Comment by sebtesobe** [comment]
@simonredfern agreed to remove 'Last Minute' from the frontend

**Comment by sebtesobe** [comment]
@simonredfern Please check https://apimanagersandbox.openbankproject.com/consumers/ (and if you have any replies please open a new issue and move the last comments over there)
